export type SystemToolCategory =
  | "agent"
  | "automation"
  | "communication"
  | "context"
  | "file"
  | "mcp"
  | "notebook"
  | "planning"
  | "shell"
  | "skill"
  | "task"
  | "team"
  | "web"
  | "worktree"
  | "internal";

export type SystemToolAvailability =
  | "base"
  | "feature_flag"
  | "environment"
  | "internal";

export type SystemToolConcurrency =
  | "safe"
  | "unsafe"
  | "input_dependent"
  | "default_unsafe";

export interface SystemToolCatalogEntry {
  name: string;
  aliases?: string[];
  category: SystemToolCategory;
  availability: SystemToolAvailability;
  description: string;
  concurrency: SystemToolConcurrency;
  readOnly: boolean | "input_dependent";
  destructive: boolean | "input_dependent";
  claudeCodeSource: string;
  implementation: "registered" | "catalog_only";
}

function entry(
  entry: Omit<SystemToolCatalogEntry, "implementation"> & {
    implementation?: SystemToolCatalogEntry["implementation"];
  },
): SystemToolCatalogEntry {
  return {
    ...entry,
    implementation: entry.implementation ?? "catalog_only",
  };
}

// Claude Code keeps these in src/tools.ts plus src/tools/* implementations.
// Skills are exposed through Skill, and MCP tools are merged into the pool later.
// This catalog is intentionally metadata-only; executable tools must still be
// registered in ToolRegistry before the gateway can call them.
export const CLAUDE_CODE_SYSTEM_TOOL_CATALOG = [
  entry({
    name: "Agent",
    aliases: ["Task"],
    category: "agent",
    availability: "base",
    description: "Run a subagent for multi-step or delegated work.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/AgentTool",
  }),
  entry({
    name: "TaskOutput",
    category: "agent",
    availability: "base",
    description: "Read output produced by an asynchronous task or subagent.",
    concurrency: "default_unsafe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/TaskOutputTool",
  }),
  entry({
    name: "Bash",
    category: "shell",
    availability: "base",
    description: "Run shell commands under the permission system.",
    concurrency: "input_dependent",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/BashTool",
    implementation: "registered",
  }),
  entry({
    name: "PowerShell",
    category: "shell",
    availability: "environment",
    description: "Run PowerShell commands when that shell tool is enabled.",
    concurrency: "input_dependent",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/PowerShellTool",
  }),
  entry({
    name: "Glob",
    category: "file",
    availability: "base",
    description: "Find files by glob pattern.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/GlobTool",
    implementation: "registered",
  }),
  entry({
    name: "Grep",
    category: "file",
    availability: "base",
    description: "Search file contents with structured result handling.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/GrepTool",
    implementation: "registered",
  }),
  entry({
    name: "Read",
    category: "file",
    availability: "base",
    description: "Read a file or supported document content.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/FileReadTool",
    implementation: "registered",
  }),
  entry({
    name: "Edit",
    category: "file",
    availability: "base",
    description: "Apply targeted replacements to an existing file.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/FileEditTool",
    implementation: "registered",
  }),
  entry({
    name: "Write",
    category: "file",
    availability: "base",
    description: "Create or overwrite file content.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/FileWriteTool",
    implementation: "registered",
  }),
  entry({
    name: "NotebookEdit",
    category: "notebook",
    availability: "base",
    description: "Edit cells in a notebook file.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/NotebookEditTool",
  }),
  entry({
    name: "WebFetch",
    category: "web",
    availability: "base",
    description: "Fetch and summarize content from a URL.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/WebFetchTool",
    implementation: "registered",
  }),
  entry({
    name: "WebSearch",
    category: "web",
    availability: "base",
    description: "Search the web through the configured search provider.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/WebSearchTool",
    implementation: "registered",
  }),
  entry({
    name: "WebBrowser",
    category: "web",
    availability: "feature_flag",
    description: "Drive a browser session when the browser tool is enabled.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "TodoWrite",
    category: "task",
    availability: "base",
    description: "Update the current todo list shown to the user.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/TodoWriteTool",
    implementation: "registered",
  }),
  entry({
    name: "TaskCreate",
    category: "task",
    availability: "feature_flag",
    description: "Create a structured task in the task system.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/TaskCreateTool",
  }),
  entry({
    name: "TaskGet",
    category: "task",
    availability: "feature_flag",
    description: "Read one task from the task system.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/TaskGetTool",
  }),
  entry({
    name: "TaskUpdate",
    category: "task",
    availability: "feature_flag",
    description: "Update a structured task.",
    concurrency: "safe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/TaskUpdateTool",
  }),
  entry({
    name: "TaskList",
    category: "task",
    availability: "feature_flag",
    description: "List tasks from the task system.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/TaskListTool",
  }),
  entry({
    name: "TaskStop",
    category: "task",
    availability: "base",
    description: "Stop an in-flight task or subagent.",
    concurrency: "safe",
    readOnly: false,
    destructive: true,
    claudeCodeSource: "claude-code-analysis/src/tools/TaskStopTool",
  }),
  entry({
    name: "EnterPlanMode",
    category: "planning",
    availability: "base",
    description: "Switch the session into plan mode.",
    concurrency: "safe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/EnterPlanModeTool",
  }),
  entry({
    name: "ExitPlanMode",
    category: "planning",
    availability: "base",
    description: "Submit a plan and leave plan mode after approval handling.",
    concurrency: "safe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/ExitPlanModeTool",
  }),
  entry({
    name: "AskUserQuestion",
    category: "communication",
    availability: "base",
    description: "Ask the user a structured clarification question.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/AskUserQuestionTool",
  }),
  entry({
    name: "SendMessage",
    category: "communication",
    availability: "base",
    description: "Send a message to a teammate or subagent.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/SendMessageTool",
  }),
  entry({
    name: "SendUserMessage",
    aliases: ["Brief"],
    category: "communication",
    availability: "base",
    description: "Send the user-facing reply in asynchronous agent flows.",
    concurrency: "safe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/BriefTool",
  }),
  entry({
    name: "Skill",
    category: "skill",
    availability: "base",
    description: "Load and execute a skill-backed command.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/SkillTool",
  }),
  entry({
    name: "ListMcpResourcesTool",
    category: "mcp",
    availability: "base",
    description: "List resources exposed by connected MCP servers.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/ListMcpResourcesTool",
  }),
  entry({
    name: "ReadMcpResourceTool",
    category: "mcp",
    availability: "base",
    description: "Read a specific resource from an MCP server.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/ReadMcpResourceTool",
  }),
  entry({
    name: "ToolSearch",
    category: "mcp",
    availability: "feature_flag",
    description: "Search deferred tool metadata and expose selected tools.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/ToolSearchTool",
  }),
  entry({
    name: "MCPTool",
    category: "mcp",
    availability: "base",
    description: "Adapter shape used for callable MCP tools.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/MCPTool",
  }),
  entry({
    name: "Config",
    category: "internal",
    availability: "internal",
    description: "Read or modify Claude Code configuration in internal builds.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/ConfigTool",
  }),
  entry({
    name: "Tungsten",
    category: "internal",
    availability: "internal",
    description: "Internal-only tool referenced by ant builds.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "REPL",
    category: "shell",
    availability: "internal",
    description: "Run primitive tools through a REPL-style VM context.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/REPLTool",
  }),
  entry({
    name: "LSP",
    category: "context",
    availability: "environment",
    description: "Query language-server information when enabled.",
    concurrency: "safe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/LSPTool",
  }),
  entry({
    name: "EnterWorktree",
    category: "worktree",
    availability: "feature_flag",
    description: "Enter a managed worktree context.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/EnterWorktreeTool",
  }),
  entry({
    name: "ExitWorktree",
    category: "worktree",
    availability: "feature_flag",
    description: "Leave a managed worktree context.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/ExitWorktreeTool",
  }),
  entry({
    name: "TeamCreate",
    category: "team",
    availability: "feature_flag",
    description: "Create a coordinated team of agents.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/TeamCreateTool",
  }),
  entry({
    name: "TeamDelete",
    category: "team",
    availability: "feature_flag",
    description: "Delete the current coordinated team.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: true,
    claudeCodeSource: "claude-code-analysis/src/tools/TeamDeleteTool",
  }),
  entry({
    name: "ListPeers",
    category: "team",
    availability: "feature_flag",
    description: "List available peer agents or sessions.",
    concurrency: "default_unsafe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "CronCreate",
    category: "automation",
    availability: "feature_flag",
    description: "Create a scheduled cron-style task.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/ScheduleCronTool",
  }),
  entry({
    name: "CronDelete",
    category: "automation",
    availability: "feature_flag",
    description: "Delete a scheduled cron-style task.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: true,
    claudeCodeSource: "claude-code-analysis/src/tools/ScheduleCronTool",
  }),
  entry({
    name: "CronList",
    category: "automation",
    availability: "feature_flag",
    description: "List scheduled cron-style tasks.",
    concurrency: "default_unsafe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/ScheduleCronTool",
  }),
  entry({
    name: "RemoteTrigger",
    category: "automation",
    availability: "feature_flag",
    description: "Register or inspect remote triggers.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/RemoteTriggerTool",
  }),
  entry({
    name: "Sleep",
    category: "automation",
    availability: "feature_flag",
    description: "Pause execution for proactive or scheduled workflows.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools/SleepTool",
    implementation: "registered",
  }),
  entry({
    name: "Monitor",
    category: "automation",
    availability: "feature_flag",
    description: "Start or manage a monitor workflow.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "Workflow",
    category: "automation",
    availability: "feature_flag",
    description: "Run bundled workflow scripts.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "SuggestBackgroundPR",
    category: "automation",
    availability: "internal",
    description: "Suggest creating a background pull request in internal builds.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "VerifyPlanExecution",
    category: "planning",
    availability: "environment",
    description: "Verify that a completed implementation matches the plan.",
    concurrency: "default_unsafe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "CtxInspect",
    category: "context",
    availability: "feature_flag",
    description: "Inspect context-collapse state in enabled builds.",
    concurrency: "default_unsafe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "TerminalCapture",
    category: "context",
    availability: "feature_flag",
    description: "Capture terminal panel state when available.",
    concurrency: "default_unsafe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "Snip",
    category: "context",
    availability: "feature_flag",
    description: "Create or manage history snippets.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "OverflowTest",
    category: "internal",
    availability: "internal",
    description: "Exercise context overflow behavior in test builds.",
    concurrency: "default_unsafe",
    readOnly: true,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "TestingPermission",
    category: "internal",
    availability: "internal",
    description: "Exercise tool permission behavior in tests.",
    concurrency: "default_unsafe",
    readOnly: "input_dependent",
    destructive: "input_dependent",
    claudeCodeSource: "claude-code-analysis/src/tools/testing",
  }),
  entry({
    name: "SendUserFile",
    category: "communication",
    availability: "feature_flag",
    description: "Send a file to the user in supported environments.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "PushNotification",
    category: "communication",
    availability: "feature_flag",
    description: "Send a push notification in supported environments.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
  entry({
    name: "SubscribePR",
    category: "communication",
    availability: "feature_flag",
    description: "Subscribe to pull-request webhook updates.",
    concurrency: "default_unsafe",
    readOnly: false,
    destructive: false,
    claudeCodeSource: "claude-code-analysis/src/tools.ts",
  }),
] as const satisfies readonly SystemToolCatalogEntry[];

export function listSystemToolCatalog(): readonly SystemToolCatalogEntry[] {
  return CLAUDE_CODE_SYSTEM_TOOL_CATALOG;
}

export function getSystemToolCatalogEntry(name: string): SystemToolCatalogEntry | undefined {
  return CLAUDE_CODE_SYSTEM_TOOL_CATALOG.find(
    tool => tool.name === name || tool.aliases?.includes(name),
  );
}
