-- qwen3-embedding:0.6b returns 1024-dimensional vectors.
-- Existing 1536-dimensional embeddings cannot be converted losslessly, so the
-- affected values are cleared and can be regenerated by subsequent memory runs.

-- 0004_memory_p0_p1 was added after another migration with a later journal
-- timestamp had already been applied in some environments. Drizzle skips such
-- retroactively-added migrations, so make this migration self-healing by
-- creating the memory tables before altering/indexing them.
CREATE EXTENSION IF NOT EXISTS vector;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "task_conversation_snapshot" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"task_id" uuid NOT NULL,
	"user_id" text NOT NULL,
	"query" text NOT NULL,
	"final_answer" text NOT NULL,
	"messages" jsonb NOT NULL,
	"tool_summary" jsonb DEFAULT '[]',
	"summary" text,
	"turns" integer NOT NULL,
	"stopped_by" text NOT NULL,
	"scenario" text,
	"entities" text[] DEFAULT '{}',
	"embedding" vector(1024),
	"is_checkpoint" boolean NOT NULL DEFAULT false,
	"checkpoint_turn" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "episodic_memories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"task_id" uuid,
	"user_id" text NOT NULL,
	"scene" text,
	"user_query" text NOT NULL,
	"tool_sequence" jsonb DEFAULT '[]',
	"final_result" text,
	"importance" double precision DEFAULT 0.5,
	"tags" text[] DEFAULT '{}',
	"related_entities" text[] DEFAULT '{}',
	"embedding" vector(1024),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'task_conversation_snapshot_task_id_tasks_id_fk'
	) THEN
		ALTER TABLE "task_conversation_snapshot"
			ADD CONSTRAINT "task_conversation_snapshot_task_id_tasks_id_fk"
			FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id")
			ON DELETE cascade ON UPDATE no action;
	END IF;

	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'episodic_memories_task_id_tasks_id_fk'
	) THEN
		ALTER TABLE "episodic_memories"
			ADD CONSTRAINT "episodic_memories_task_id_tasks_id_fk"
			FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id")
			ON DELETE cascade ON UPDATE no action;
	END IF;
END
$$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_conv_snapshot_task_id_idx"
	ON "task_conversation_snapshot" USING btree ("task_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_conv_snapshot_user_id_idx"
	ON "task_conversation_snapshot" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_conv_snapshot_checkpoint_idx"
	ON "task_conversation_snapshot" USING btree ("task_id", "is_checkpoint");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "episodic_memories_user_id_idx"
	ON "episodic_memories" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "episodic_memories_scene_idx"
	ON "episodic_memories" USING btree ("scene");
--> statement-breakpoint

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM pg_attribute attribute
		JOIN pg_class relation ON relation.oid = attribute.attrelid
		JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace
		WHERE namespace.nspname = 'public'
			AND relation.relname = 'task_conversation_snapshot'
			AND attribute.attname = 'embedding'
			AND NOT attribute.attisdropped
			AND format_type(attribute.atttypid, attribute.atttypmod) <> 'vector(1024)'
	) THEN
		DROP INDEX IF EXISTS "task_conv_snapshot_embedding_idx";
		ALTER TABLE "task_conversation_snapshot"
			ALTER COLUMN "embedding" TYPE vector(1024)
			USING NULL::vector(1024);
	END IF;
END
$$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_conv_snapshot_embedding_idx"
	ON "task_conversation_snapshot"
	USING ivfflat ("embedding" vector_cosine_ops)
	WITH (lists = 100);
--> statement-breakpoint
DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM pg_attribute attribute
		JOIN pg_class relation ON relation.oid = attribute.attrelid
		JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace
		WHERE namespace.nspname = 'public'
			AND relation.relname = 'episodic_memories'
			AND attribute.attname = 'embedding'
			AND NOT attribute.attisdropped
			AND format_type(attribute.atttypid, attribute.atttypmod) <> 'vector(1024)'
	) THEN
		DROP INDEX IF EXISTS "episodic_memories_embedding_idx";
		ALTER TABLE "episodic_memories"
			ALTER COLUMN "embedding" TYPE vector(1024)
			USING NULL::vector(1024);
	END IF;
END
$$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "episodic_memories_embedding_idx"
	ON "episodic_memories"
	USING ivfflat ("embedding" vector_cosine_ops)
	WITH (lists = 100);
