-- qwen3-embedding:0.6b returns 1024-dimensional vectors.
-- Existing 1536-dimensional embeddings cannot be converted losslessly, so the
-- affected values are cleared and can be regenerated by subsequent memory runs.

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM pg_attribute attribute
		JOIN pg_class relation ON relation.oid = attribute.attrelid
		JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace
		WHERE namespace.nspname = 'public'
			AND relation.relname = 'task_conversation_snapshot'
			AND attribute.attname = 'embedding'
			AND NOT attribute.attisdropped
			AND format_type(attribute.atttypid, attribute.atttypmod) <> 'vector(1024)'
	) THEN
		DROP INDEX IF EXISTS "task_conv_snapshot_embedding_idx";
		ALTER TABLE "task_conversation_snapshot"
			ALTER COLUMN "embedding" TYPE vector(1024)
			USING NULL::vector(1024);
	END IF;
END
$$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_conv_snapshot_embedding_idx"
	ON "task_conversation_snapshot"
	USING ivfflat ("embedding" vector_cosine_ops)
	WITH (lists = 100);
--> statement-breakpoint
DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM pg_attribute attribute
		JOIN pg_class relation ON relation.oid = attribute.attrelid
		JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace
		WHERE namespace.nspname = 'public'
			AND relation.relname = 'episodic_memories'
			AND attribute.attname = 'embedding'
			AND NOT attribute.attisdropped
			AND format_type(attribute.atttypid, attribute.atttypmod) <> 'vector(1024)'
	) THEN
		DROP INDEX IF EXISTS "episodic_memories_embedding_idx";
		ALTER TABLE "episodic_memories"
			ALTER COLUMN "embedding" TYPE vector(1024)
			USING NULL::vector(1024);
	END IF;
END
$$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "episodic_memories_embedding_idx"
	ON "episodic_memories"
	USING ivfflat ("embedding" vector_cosine_ops)
	WITH (lists = 100);
